name: Node Test

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Install imagemagick
      run: sudo apt install imagemagick ghostscript
    - name: Change ImageMagick policy to allow pdf->png conversion.
      run: sudo sed -i 's/^.*policy.*coder.*none.*PDF.*//' /etc/ImageMagick-6/policy.xml
    - name: npm test
      run: |
        npm ci
        npm test
      env:
        CI: true
